spring.application.name=SistemaGestionHotel
server.port=8082
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pruebasJuan;encrypt=false;trustServerCertificate=true
spring.datasource.username=DESKTOP-EKNJ6JS\USER
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# --- Propiedades de JWT ---
jwt.secret.key=Kc3201q49*

# Tiempo de vida del token en milisegundos
jwt.time.expiration=86400000